version: '3.0'

expectations:
  population_size: 2000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_cohort --output-format dta
    outputs:
      highly_sensitive:
        cohort: output/input_cohort.dta

  count_by_strata:
    run: python:latest python analysis/all_time_counts.py
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        table: output/counts_table.csv

  logistic_models:
    run: stata-mp:latest analysis/model.do
    needs: [generate_cohort]
    outputs:
      moderately_sensitive:
        table: output/model_summary.csv
        log: logs/models.log
